default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: giv2giv_development

test:
  <<: *default
  database: giv2giv_test

production:
  <<: *default
  database: giv2giv_production
